import { test, expect } from '@playwright/test';
import { login, bridge } from './helpers.js';
test('room panel persistence, unchanged geometry, chat draft and stale review', async ({ page }) => {
  await login(page);
  const panel = page.getByRole('complementary', { name: '需求收集面板' });
  const before = await bridge(page, 'snapshot', {});
  await page.locator('#living-purpose').fill('阅读和家庭活动');
  await panel.getByRole('button', { name: '保存用途', exact: true }).click();
  await expect(panel.locator('[data-field="purpose"]')).toContainText('业主填写');
  await panel.getByRole('button', { name: '房间 2', exact: true }).click();
  await page.locator('#room2-purpose').fill('宝宝房');
  await panel.getByRole('button', { name: '保存用途', exact: true }).click();
  await expect(panel.locator('[data-field="purpose"]')).toContainText('业主填写');
  await panel.getByRole('button', { name: '客厅', exact: true }).click();
  await expect(page.locator('#living-purpose')).toHaveValue('阅读和家庭活动');
  await page.locator('#living-target_width').fill('5.2');
  await panel.getByRole('button', { name: '保存目标宽度（米）', exact: true }).click();
  await expect(panel.locator('[data-field="target_width"]')).toContainText('待专业测量');
  const after = await bridge(page, 'snapshot', {});
  expect(after.scene.floors[0].walls).toEqual(before.scene.floors[0].walls);
  await panel.getByLabel('总预算回答状态').selectOption('unknown');
  await panel.getByRole('button', { name: '保存总预算', exact: true }).click();
  await expect(panel.locator('[data-field="budget"]')).toContainText('暂不确定');
  const panelWidth = (await bridge(page, 'inspect', {})).camera.width;
  await page.getByRole('button', { name: '收起需求面板' }).click();
  await expect.poll(async () => (await bridge(page, 'inspect', {})).camera.width).toBeGreaterThan(panelWidth);
  await page.reload();
  await expect(page.locator('#living-purpose')).toHaveValue('阅读和家庭活动');
  await expect(page.locator('#living-target_width')).toHaveValue('5.2');
  await page.getByRole('button', { name: '收起需求面板' }).click();
  await page.getByRole('button', { name: /聊聊你的家/ }).click();
  const input = page.getByRole('textbox', { name: '咨询消息' });
  await input.fill('这是一条尚未发送的测试草稿');
  const keyboardBefore = await bridge(page, 'snapshot', {});
  const cameraBefore = (await bridge(page, 'inspect', {})).camera.position;
  await input.press('Delete');
  await input.press('ArrowLeft');
  expect((await bridge(page, 'snapshot', {})).scene).toEqual(keyboardBefore.scene);
  expect((await bridge(page, 'inspect', {})).camera.position).toEqual(cameraBefore);
  await page.setViewportSize({width:375,height:812});
  await expect(input).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:'docs/evidence/week1/03-mobile-chat.png',fullPage:true});
  await page.setViewportSize({width:1440,height:960});
  await page.getByRole('button', { name: '收起聊天' }).click();
  await page.getByRole('button', { name: /聊聊你的家/ }).click();
  await expect(input).toHaveValue('这是一条尚未发送的测试草稿');
  await page.getByRole('button', { name: '收起聊天' }).click();
  await page.getByRole('button', { name: '需求任务书', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('button', { name: '仅运行规则检查' }).click();
  await expect(dialog).toContainText('预算币种或包含范围未知');
  await expect(dialog).toContainText('对应当前需求版本');
  await page.getByRole('button', { name: '关闭任务书' }).click();
  await page.getByRole('button', { name: /需求清单/ }).click();
  await page.locator('#living-target_width').fill('5.3');
  await panel.getByRole('button', { name: '保存目标宽度（米）', exact: true }).click();
  await page.getByRole('button', { name: '需求任务书', exact: true }).click();
  await expect(dialog).toContainText('报告已过期');
  await page.screenshot({ path: 'docs/evidence/week1/02-05-brief.png', fullPage: true });
});
