import {test, expect} from '@playwright/test';
import {writeFileSync} from 'node:fs';
import {login} from './helpers.js';
import { evidencePath } from './evidence.js';
test('live consultation: streamed suggestions, explicit adoption, cancellation and reconnect', async ({page, context}) => {
  test.setTimeout(180000);
  await login(page);
  const id = await page.locator('iframe').getAttribute('src').then(s => new URL(s!, 'http://127.0.0.1:4175').searchParams.get('project'));
  const snapshot = async () => (await page.request.get(`/api/projects/${id}`)).json();
  await page.getByRole('button',{name:/聊聊你的家/}).click();
  const text = `合成浏览器验收 ${Date.now()}：客厅希望兼顾阅读、衣物收纳和婴儿照护，色调希望自然柔和。预算暂不确定。请调用 propose_field 分别给当前客厅 functions 和 tone 各一条待采用建议。不要替我采用，也不要改变预算。`;
  await page.getByRole('textbox',{name:'咨询消息'}).fill(text);
  await page.getByRole('button',{name:'发送咨询消息',exact:true}).click();
  await expect(page.locator('.chat-message.user').filter({hasText:text})).toHaveCount(1);
  await expect.poll(async () => (await snapshot()).messages.at(-1)?.status,{timeout:90000}).toBe('complete');
  let p = await snapshot();
  const proposals = p.suggestions.filter((s:any)=>s.status==='proposed' && s.room_id==='living');
  expect(proposals.map((s:any)=>s.field_key)).toEqual(expect.arrayContaining(['functions','tone']));
  expect(await page.locator('.chat-window:not([hidden]) .ask-card').count()).toBeLessThanOrEqual(2);
  await page.getByRole('button',{name:'收起聊天'}).click();
  const field = page.locator('.requirement-field[data-field="functions"]');
  await expect(field).toContainText('AI 建议 · 未采用');
  await page.getByRole('button',{name:'保存项目',exact:true}).click();
  await expect(page.locator('.project-name')).toContainText('后端已保存');
  expect((await snapshot()).suggestions.filter((s:any)=>s.status==='proposed').length).toBe(proposals.length);
  let adoptedScope = '';
  page.once('dialog', async dialog => {
    adoptedScope = dialog.message();
    await dialog.dismiss();
  });
  await page.getByRole('button',{name:/审阅并采用本房间/}).click();
  expect(adoptedScope).toContain('色调');
  expect(adoptedScope).toContain('功能');
  expect((await snapshot()).suggestions.filter((s:any)=>s.status==='proposed').length).toBe(proposals.length);
  await field.getByRole('button',{name:'采用此字段'}).click();
  await expect(field).toContainText('已采用');
  p = await snapshot();
  expect(p.suggestions.find((s:any)=>s.field_key==='tone' && s.status==='proposed')).toBeTruthy();
  expect(p.requirements.find((r:any)=>r.field_key==='functions' && r.room_id==='living').source).toBe('accepted');
  await context.setOffline(true);
  await expect(page.locator('.project-name')).toContainText('重连');
  await context.setOffline(false);
  await expect(page.locator('.project-name')).toContainText('已同步');
  await page.getByRole('button',{name:/聊聊你的家/}).click();
  await expect(page.locator('.chat-message.user').filter({hasText:text})).toHaveCount(1);
  const cancelText = `取消验收 ${Date.now()}：请整理当前需求。`;
  await page.getByRole('textbox',{name:'咨询消息'}).fill(cancelText);
  await page.getByRole('button',{name:'发送咨询消息',exact:true}).click();
  await page.getByRole('button',{name:'停止本轮',exact:true}).click();
  await expect.poll(async () => (await snapshot()).messages.at(-1)?.status).toBe('cancelled');
  await page.reload();
  await page.getByRole('button',{name:/聊聊你的家/}).click();
  await expect(page.locator('.chat-message.user').filter({hasText:cancelText})).toHaveCount(1);
  p=await snapshot();
  expect(new Set(p.messages.map((m:any)=>m.id)).size).toBe(p.messages.length);
  writeFileSync(evidencePath('live-browser.json'), JSON.stringify({passed:true,synthetic:true,real_provider:true,proposal_fields:proposals.map((s:any)=>s.field_key),explicit_group_scope:adoptedScope,cancelled_input_retained:true,reconnected_without_duplicate:true,budget:p.requirements.find((r:any)=>r.field_key==='budget')?.value},null,2));
});
