import {test,expect} from '@playwright/test';
import {login,bridge} from './helpers.js';
import {evidencePath} from './evidence.js';
test('furniture click edit save reload and failed update restores draft; mobile focus',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('net::ERR_FAILED'))errors.push(m.text());});
 await login(page);
 const camera=(await bridge(page,'inspect',{})).camera;
 const sofa=camera.objects.find((o:any)=>o.id==='sofa-main');
 await page.frameLocator('iframe').locator('canvas').first().click({position:{x:sofa.x,y:sofa.y}});
 await expect(page.locator('.selection')).toContainText('sofa-main');
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByLabel('宽度（cm）').fill('231');
 await page.getByLabel('进深（cm）').fill('101');
 await page.getByLabel('物件高度（cm）').fill('95');
 await page.getByLabel('颜色',{exact:true}).fill('#aa3344');
 await page.getByLabel('离地高度（cm）').fill('22');
 const selected=(await bridge(page,'inspect',{}));
 expect(selected.selected).toBe('sofa-main');
 expect(selected.camera.objects.find((o:any)=>o.id==='sofa-main').highlighted).toContain('sofa-main');
 await expect(page.getByLabel('材质',{exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'确认保存家具'}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await expect.poll(async()=> (await bridge(page,'snapshot',{})).scene.floors[0].furniture.find((o:any)=>o.id==='sofa-main').width).toBe(231);
 await page.reload();
 await expect(page.getByRole('button',{name:'保存项目',exact:true})).toBeEnabled();
 const rendered=(await bridge(page,'inspect',{})).camera.objects.find((o:any)=>o.id==='sofa-main');
 expect(rendered.bounds.size[0]).toBeCloseTo(231,3);
 expect(rendered.bounds.size[1]).toBeCloseTo(95,3);
 expect(rendered.bounds.size[2]).toBeCloseTo(101,3);
 expect(rendered.bounds.min[1]).toBeCloseTo(23.5,3);
 expect(rendered.colors).toContain('#aa3344');
 await page.screenshot({path:evidencePath('06-desktop.png')});
 await page.locator('iframe').focus();
 await bridge(page,'select',{object_id:'sofa-main'});
 await expect(page.getByRole('dialog')).toBeVisible();
 await expect(page.getByLabel('离地高度（cm）')).toHaveValue('22');
 const projectId=await page.locator('iframe').evaluate((e:HTMLIFrameElement)=>new URL(e.src).searchParams.get('project'));
 const current=await (await page.request.get(`/api/projects/${projectId}`)).json();
 const stale=await page.request.post(`/api/projects/${projectId}/objects/update`,{data:{expected_version:current.version-1,request_id:crypto.randomUUID(),room_id:'living',object_id:'sofa-main',confirmed:true,patch:{width:250}}});
 expect(stale.status()).toBe(409);
 const unsupported=await page.request.post(`/api/projects/${projectId}/objects/update`,{data:{expected_version:current.version,request_id:crypto.randomUUID(),room_id:'living',object_id:'sofa-main',confirmed:true,patch:{material:'wood'}}});
 expect(unsupported.status()).toBe(400);
 expect((await (await page.request.get(`/api/projects/${projectId}`)).json()).version).toBe(current.version);
 await page.route('**/objects/update',r=>r.abort());
 await page.getByLabel('宽度（cm）').fill('250');
 await page.getByRole('button',{name:'确认保存家具'}).click();
 await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();
 await expect(page.getByLabel('宽度（cm）')).toHaveValue('231');
 await page.setViewportSize({width:375,height:812});
 const box=await page.getByRole('dialog').boundingBox();
 expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(375);
 await page.screenshot({path:evidencePath('06-mobile.png')});
 await page.getByRole('button',{name:'关闭家具属性'}).click();
 await expect(page.locator('iframe')).toBeFocused();
 expect(errors).toEqual([]);
});
