import {test,expect} from '@playwright/test';
import {login,bridge} from './helpers.js';
import {evidencePath} from './evidence.js';
test('real Pi object chat stays pending, native preview cancels, explicit adoption survives reload',async({page})=>{
 test.setTimeout(150000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('409 (Conflict)'))errors.push(m.text());});
 await login(page);
 await bridge(page,'select',{object_id:'sofa-main'});
 const scope=page.getByRole('region',{name:'当前家具聊天'});
 await expect(scope).toBeVisible();
 const projectId=await page.locator('iframe').evaluate((e:HTMLIFrameElement)=>new URL(e.src).searchParams.get('project'));
 const read=async()=>(await page.request.get(`/api/projects/${projectId}`)).json();
 const before=await read();const sofa=before.scene.floors[0].furniture.find((o:any)=>o.id==='sofa-main');
 await scope.getByLabel('对这件家具的要求').fill('请仅建议将此沙发宽度改为239厘米，其他参数完全不变。调用建议工具，等待我确认。');
 const response=page.waitForResponse(r=>r.url().endsWith('/objects/chat')&&r.request().method()==='POST',{timeout:90000});
 await scope.getByRole('button',{name:'发送家具要求'}).click();
 const http=await response;expect(http.status()).toBe(200);const generated=await http.json();
 const latest=generated.object_messages.at(-1);expect(latest.object_id).toBe('sofa-main');expect(latest.room_id).toBe('living');expect(latest.patch).toEqual({width:239});expect(latest.status).toBe('proposed');expect(generated.scene).toEqual(before.scene);
 await expect(scope.getByText('AI 建议 · 未采用').last()).toBeVisible();
 await scope.getByRole('button',{name:'预览此家具'}).last().click();
 await expect.poll(async()=>(await bridge(page,'inspect',{})).camera.objects.find((o:any)=>o.id==='sofa-main').bounds.size[0]).toBeCloseTo(239,2);
 expect((await read()).scene).toEqual(before.scene);
 await page.getByRole('button',{name:'关闭家具属性'}).click();
 await expect.poll(async()=>(await bridge(page,'snapshot',{})).scene.floors[0].furniture.find((o:any)=>o.id==='sofa-main').width).toBe(sofa.width);
 await bridge(page,'select',{object_id:'sofa-main'});
 await scope.getByRole('button',{name:'预览此家具'}).last().click();
 await page.screenshot({path:evidencePath('07-desktop.png')});
 await page.setViewportSize({width:375,height:812});await scope.getByRole('button',{name:'确认采用此建议'}).last().scrollIntoViewIfNeeded();await page.screenshot({path:evidencePath('07-mobile.png')});
 await scope.getByRole('button',{name:'确认采用此建议'}).last().click();
 await expect.poll(async()=>(await read()).object_messages.at(-1).status).toBe('accepted');
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await bridge(page,'select',{object_id:'sofa-main'});await expect(page.getByLabel('宽度（cm）')).toHaveValue('239');
 await page.getByLabel('颜色',{exact:true}).fill('#335577');await page.getByRole('button',{name:'确认保存家具'}).click();
 expect((await read()).scene.floors[0].furniture.find((o:any)=>o.id==='sofa-main').width).toBe(239);
 await bridge(page,'select',{object_id:'sofa-main'});await expect(page.getByLabel('宽度（cm）')).toHaveValue('239');await page.getByLabel('颜色',{exact:true}).fill('#553377');
 const external=await read();expect((await page.request.post(`/api/projects/${projectId}/objects/update`,{data:{expected_version:external.version,request_id:crypto.randomUUID(),room_id:'living',object_id:'sofa-main',confirmed:true,patch:{width:255}}})).status()).toBe(200);
 const stale=page.waitForResponse(r=>r.url().endsWith('/objects/update')&&r.request().method()==='POST');await page.getByRole('button',{name:'确认保存家具'}).click();expect((await stale).status()).toBe(409);await expect(page.getByLabel('颜色',{exact:true})).toHaveValue('#553377');expect((await read()).scene.floors[0].furniture.find((o:any)=>o.id==='sofa-main').width).toBe(255);
 await page.getByRole('button',{name:'读取最新值并重新核对'}).click();await expect(page.getByLabel('宽度（cm）')).toHaveValue('255');await page.getByLabel('宽度（cm）').fill('239');await page.getByRole('button',{name:'确认保存家具'}).click();
 await page.reload();await expect(page.getByRole('button',{name:'保存项目',exact:true})).toBeEnabled();
 await expect.poll(async()=>(await bridge(page,'inspect',{})).camera.objects.find((o:any)=>o.id==='sofa-main').bounds.size[0]).toBeCloseTo(239,2);
 await bridge(page,'select',{object_id:'sofa-main'});await expect(scope.getByText('已明确采用').last()).toBeVisible();
 await page.getByRole('button',{name:'关闭家具属性'}).click();
 const another=(await read()).scene.floors[0].furniture.find((o:any)=>o.id!=='sofa-main');await bridge(page,'select',{object_id:another.id});await expect(scope).toBeVisible();await expect(scope.getByText(latest.raw_user_evidence,{exact:false})).toHaveCount(0);
 expect(errors).toEqual([]);
});
