import {test,expect} from '@playwright/test';import {resolve} from 'node:path';import {login} from './helpers.js';import {evidencePath} from './evidence.js';
test('simulated microphone: real MediaRecorder WAV conversion, original preservation, cancellation and denial',async({page,context})=>{
 test.setTimeout(120000);await page.addInitScript(()=>{
 // Explicit fixture: ONLY getUserMedia is substituted. Encoder, WAV conversion and APIs are real.
 const w=window as any;w.testStreams=[];w.denyCapture=false;w.delayCapture=false;
 navigator.mediaDevices.getUserMedia=async()=>{
  if(w.denyCapture)throw new DOMException('Permission denied by simulated test fixture','NotAllowedError');
  const audio=new AudioContext();await audio.resume();const tone=audio.createOscillator();const gain=audio.createGain();gain.gain.value=0.1;tone.frequency.value=440;const destination=audio.createMediaStreamDestination();tone.connect(gain);gain.connect(destination);tone.start();w.testStreams.push(destination.stream);
  if(w.delayCapture)await new Promise<void>(resolve=>{w.resolveCapture=resolve;});return destination.stream;
 };
 });await login(page);const id=new URL(page.url()).searchParams.get('project');const read=async()=>(await page.request.get(`/api/projects/${id}`)).json();await page.getByRole('button',{name:/聊聊你的家/}).click();const chat=page.getByRole('region',{name:'客厅咨询聊天',exact:true});const media=chat.locator('.media-input');await media.getByRole('button',{name:'语音与参考图片',exact:true}).click();await media.getByRole('button',{name:'开始录音'}).click();await expect(media.getByRole('button',{name:'停止录音'})).toBeEnabled();await page.waitForTimeout(2200);await media.getByRole('button',{name:'停止录音'}).click();await expect(media.getByRole('button',{name:'转写音频'})).toBeVisible();const p=await read();expect(p.attachments).toHaveLength(1);const original=await page.request.get(`/api/projects/${id}/media/${p.attachments[0].id}?original=1`);expect(original.headers()['content-type']).toContain('audio/webm');expect((await original.body()).subarray(0,4).toString('hex')).toBe('1a45dfa3');const normalized=await page.request.get(`/api/projects/${id}/media/${p.attachments[0].id}`);expect((await normalized.body()).toString('ascii',8,12)).toBe('WAVE');
 await media.getByRole('button',{name:'开始录音'}).click();await expect(media.getByRole('button',{name:'取消录音'})).toBeEnabled();await media.getByRole('button',{name:'取消录音'}).click();expect((await read()).attachments).toHaveLength(1);await expect.poll(()=>page.evaluate(()=>(window as any).testStreams.every((s:MediaStream)=>s.getTracks().every(t=>t.readyState==='ended')))).toBe(true);
 await media.getByRole('button',{name:'开始录音'}).click();await expect(media.getByRole('button',{name:'停止录音'})).toBeEnabled();await chat.getByRole('button',{name:'收起聊天'}).click();await expect.poll(()=>page.evaluate(()=>(window as any).testStreams.every((s:MediaStream)=>s.getTracks().every(t=>t.readyState==='ended')))).toBe(true);expect((await read()).attachments).toHaveLength(1);
 await page.getByRole('button',{name:/聊聊你的家/}).click();await page.evaluate(()=>{(window as any).delayCapture=true;});await media.getByRole('button',{name:'开始录音'}).click();await expect.poll(()=>page.evaluate(()=>typeof (window as any).resolveCapture)).toBe('function');await chat.getByRole('button',{name:'收起聊天'}).click();await page.evaluate(()=>{(window as any).resolveCapture();(window as any).delayCapture=false;});await expect.poll(()=>page.evaluate(()=>(window as any).testStreams.every((s:MediaStream)=>s.getTracks().every(t=>t.readyState==='ended')))).toBe(true);expect((await read()).attachments).toHaveLength(1);
 await page.getByRole('button',{name:/聊聊你的家/}).click();await page.evaluate(()=>{(window as any).denyCapture=true;});await media.getByRole('button',{name:'开始录音'}).click();await expect(media.getByRole('alert').filter({hasText:'权限被拒绝'})).toContainText('权限被拒绝');await media.getByRole('alert').filter({hasText:'权限被拒绝'}).scrollIntoViewIfNeeded();await page.screenshot({path:evidencePath('09-simulated-microphone-denial.png')});await page.setViewportSize({width:375,height:812});await media.getByRole('alert').filter({hasText:'权限被拒绝'}).scrollIntoViewIfNeeded();await page.screenshot({path:evidencePath('09-simulated-microphone-mobile.png')});
});
