import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {login,bridge} from './helpers.js';
import {evidencePath} from './evidence.js';
const projectId=(url:string)=>new URL(url).searchParams.get('project');

test('v2 desktop: persistent composer draft, complete questionnaire, structured budget, consent and fixed-version deliverables',async({page})=>{
 test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await login(page);const id=projectId(page.url());
 await page.getByRole('button',{name:/聊聊你的家/}).click();const chat=page.getByRole('region',{name:'客厅咨询聊天',exact:true});
 const toolbar=chat.getByRole('toolbar',{name:'聊天输入工具栏'});await expect(toolbar.getByRole('button',{name:'开始录音'})).toBeVisible();await expect(toolbar.getByRole('button',{name:'添加图片或附件'})).toBeVisible();
 const input=chat.getByRole('textbox',{name:'咨询消息'});await input.fill('这个房间的草稿先不发送');await chat.getByRole('button',{name:'收起聊天'}).click();await page.getByRole('button',{name:/聊聊你的家/}).click();await expect(input).toHaveValue('这个房间的草稿先不发送');
 const inputBox=await input.boundingBox(),toolsBox=await toolbar.boundingBox();expect(toolsBox!.y).toBeGreaterThanOrEqual(inputBox!.y+inputBox!.height-2);expect(await chat.locator('input[type=radio]:checked').count()).toBe(0);
 await toolbar.getByRole('button',{name:'添加图片或附件'}).click();await expect(page.getByRole('menuitem',{name:'文档 / 户型资料'})).toBeVisible();await page.screenshot({path:evidencePath('17-composer-desktop.png')});await page.keyboard.press('Escape');
 await chat.getByRole('button',{name:'完整问卷 · 60题'}).click();const questionnaire=page.getByRole('dialog',{name:'完整需求问卷'});await expect(questionnaire.getByRole('navigation',{name:'问卷题目索引'}).getByRole('button')).toHaveCount(60);
 await questionnaire.getByRole('navigation').getByRole('button',{name:/Q19/}).click();await questionnaire.getByLabel('自由填写问卷答案').fill('预算优先保证日常使用，不先锁定品牌');await questionnaire.getByLabel('预算目标',{exact:true}).fill('50000');await questionnaire.getByLabel('预算硬上限').fill('65000');await questionnaire.getByLabel('预算币种代码').fill('SGD');await questionnaire.getByRole('button',{name:'确认此回答',exact:true}).click();
 await expect.poll(async()=>{const p=await (await page.request.get(`/api/projects/${id}`)).json();return p.intake_answers?.find((a:any)=>a.question_id==='Q19')?.budget?.ceiling;}).toBe(65000);
 await questionnaire.getByRole('navigation').getByRole('button',{name:/Q06/}).click();await questionnaire.getByLabel('共享范围',{exact:true}).selectOption('summary');await questionnaire.getByRole('button',{name:'确认此回答',exact:true}).click();
 await questionnaire.getByRole('navigation').getByRole('button',{name:/Q13/}).click();await questionnaire.getByLabel('自由填写问卷答案').fill('温暖、安静，保留自己的生活痕迹');await questionnaire.getByRole('button',{name:'确认此回答',exact:true}).click();await questionnaire.getByRole('navigation').getByRole('button',{name:/Q38/}).click();await page.screenshot({path:evidencePath('17-questionnaire-desktop.png')});await questionnaire.getByRole('button',{name:'关闭完整问卷'}).click();
 await chat.getByRole('button',{name:'交付清单',exact:true}).click();const delivery=page.getByRole('dialog',{name:'问卷交付清单'});await expect(delivery.getByText(/温暖、安静，保留自己的生活痕迹/).first()).toBeVisible();await delivery.getByRole('button',{name:'设计师需求交接',exact:true}).click();await expect(delivery.getByRole('button',{name:'保存当前交付快照'})).toBeEnabled();await delivery.getByRole('button',{name:'保存当前交付快照'}).click();await expect(delivery.getByRole('link',{name:'下载JSON'}).first()).toBeVisible();
 const downloadPromise=page.waitForEvent('download');await delivery.getByRole('link',{name:'下载JSON'}).first().click();const download=await downloadPromise;expect(await download.failure()).toBeNull();const data=JSON.parse(await readFile((await download.path())!,'utf8'));expect(data.audience).toBe('designer');expect(data.evidence).toEqual([]);expect(data.answers.find((a:any)=>a.question_id==='Q19').budget.ceiling).toBe(65000);expect(data.sections.find((s:any)=>s.id==='D10').state).toBe('missing');await download.saveAs(evidencePath('17-designer-delivery.json'));await page.screenshot({path:evidencePath('17-delivery-desktop.png')});
 await delivery.getByRole('button',{name:'关闭交付清单'}).click();await chat.getByRole('button',{name:'收起聊天'}).click();await expect.poll(async()=>{const inspected=await bridge(page,'inspect',{});return inspected.keyboardLocked;}).not.toBe(true);expect(errors).toEqual([]);
});

test('v2 mobile: document upload, previews, remove-only-reference, room isolation and unsupported attachment feedback',async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width:375,height:812});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await login(page);const id=projectId(page.url());await page.getByRole('button',{name:/聊聊你的家/}).click();const chat=page.getByRole('region',{name:'客厅咨询聊天',exact:true});
 await expect(chat.getByRole('toolbar')).toBeVisible();for(const name of ['添加图片或附件','开始录音','发送咨询消息']){const box=await chat.getByRole('button',{name,exact:true}).boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(375);}
 await chat.getByLabel('上传文档附件').setInputFiles([{name:'家具保留清单.txt',mimeType:'text/plain',buffer:Buffer.from('保留旧餐桌，先测量实际尺寸。')},{name:'生活偏好.md',mimeType:'text/markdown',buffer:Buffer.from('# 希望\n工作日回家可以阅读，东西容易归位。')}]);
 await expect(chat.locator('.composer-file[data-state=ready]')).toHaveCount(2);const p=await (await page.request.get(`/api/projects/${id}`)).json();expect(p.attachments).toHaveLength(2);expect(p.messages).toHaveLength(0);expect(p.attachments.every((a:any)=>a.room_id==='living'&&a.extracted_text.length>0)).toBeTruthy();
 await chat.getByRole('button',{name:'移除本轮附件 家具保留清单.txt',exact:true}).click();await expect(chat.locator('.composer-file')).toHaveCount(1);expect((await (await page.request.get(`/api/projects/${id}`)).json()).attachments).toHaveLength(2);await chat.getByLabel('咨询消息',{exact:true}).fill('先保留这些想法');await page.screenshot({path:evidencePath('17-composer-documents-mobile.png')});
 await chat.getByRole('button',{name:'收起聊天'}).click();await page.locator('.room-pills button').nth(1).click();await page.getByRole('button',{name:/聊聊你的家/}).click();const other=page.getByRole('region',{name:'房间 2咨询聊天',exact:true});await expect(other.getByLabel('咨询消息',{exact:true})).toHaveValue('');await expect(other.locator('.composer-file')).toHaveCount(0);await other.getByRole('button',{name:'收起聊天'}).click();await page.locator('.room-pills button').first().click();await page.getByRole('button',{name:/聊聊你的家/}).click();await expect(chat.getByLabel('咨询消息',{exact:true})).toHaveValue('先保留这些想法');await expect(chat.locator('.composer-file')).toHaveCount(1);
 await chat.getByRole('button',{name:'完整问卷 · 60题'}).click();const q=page.getByRole('dialog',{name:'完整需求问卷'});await q.getByRole('navigation').getByRole('button',{name:/Q38/}).click();await expect(q.getByLabel('自由填写问卷答案')).toBeVisible();await page.screenshot({path:evidencePath('17-questionnaire-mobile.png')});await q.getByRole('button',{name:'关闭完整问卷'}).click();
 await chat.getByLabel('上传文档附件').setInputFiles({name:'unsupported.html',mimeType:'text/html',buffer:Buffer.from('<h1>Not accepted</h1>')});await expect(chat.getByRole('alert').filter({hasText:'不支持该类型'})).toBeVisible();expect((await (await page.request.get(`/api/projects/${id}`)).json()).attachments).toHaveLength(2);await page.screenshot({path:evidencePath('17-attachment-error-mobile.png')});expect(errors).toEqual([]);
});

test('v2 live Agent: evidence-grounded recommendation plus three alternatives, explicit one-answer adoption',async({page})=>{
 test.setTimeout(150000);await login(page);const id=projectId(page.url());await page.getByRole('button',{name:/聊聊你的家/}).click();const chat=page.getByRole('region',{name:'客厅咨询聊天',exact:true});await chat.getByLabel('咨询消息',{exact:true}).fill('本次咨询的目标是拿到清楚的需求任务书。我在家经常读书，希望以后可以调整房间。请先读取已有资料，再对尚未回答的Q38使用ask_intake_question生成一个有依据的推荐和三个实质不同的替代选项；Q38目前只是在比较方向，不要替我填写或采用。');await chat.getByRole('button',{name:'发送咨询消息',exact:true}).click();
 await expect.poll(async()=>{const p=await (await page.request.get(`/api/projects/${id}`)).json();return p.messages.findLast((m:any)=>m.role==='assistant')?.status;},{timeout:100000}).toBe('complete');
 const p=await (await page.request.get(`/api/projects/${id}`)).json();const proposal=p.intake_questions?.find((q:any)=>q.question.questionnaire_id==='Q38');expect(proposal,'The real configured provider must call the structured question tool, not only emit prose').toBeTruthy();const question=proposal.question;expect(question.generation).toBe('agent');expect(question.options).toHaveLength(4);expect(new Set(question.options.map((o:any)=>o.label)).size).toBe(4);expect(question.recommendation.evidence_ids.every((id:string)=>p.evidence.some((e:any)=>e.id===id))).toBeTruthy();expect(p.intake_answers?.some((a:any)=>a.question_id==='Q38'&&a.confirmation_state==='confirmed')).not.toBe(true);
 const card=chat.locator('[data-question-id="living:Q38"]');await expect(card).toBeVisible();expect(await card.locator('input[type=radio]:checked').count()).toBe(0);await card.locator('input[type=radio]').nth(1).check();await page.screenshot({path:evidencePath('17-agent-recommended-question.png')});await card.getByRole('button',{name:'确认此回答',exact:true}).click();await expect.poll(async()=>{const saved=await (await page.request.get(`/api/projects/${id}`)).json();return saved.intake_answers?.find((a:any)=>a.question_id==='Q38')?.answer_text;}).toBe(question.options[1].value);
 const saved=await (await page.request.get(`/api/projects/${id}`)).json();expect(saved.intake_answers.find((a:any)=>a.question_id==='Q38').source).toBe('owner');expect(JSON.stringify(saved.scene)).toBe(JSON.stringify(p.scene));
});
