import {test} from 'node:test';import assert from 'node:assert/strict';import {sampleProject} from '../apps/api/sample.js';import {recomputeGeometry} from '../apps/api/geometry.js';import {Store} from '../apps/api/store.js';
const active=(p:any,rule:string)=>p.geometry_diagnostics.filter((d:any)=>d.status==='active'&&d.rule===rule);
test('occupied boxes: rotated hit, vertical separation, rug exclusion, boundary and unknown',()=>{const p=sampleProject('geometry');const f=p.scene.floors[0];f.furniture=f.furniture.filter(o=>['sofa-main','chair-main','rug-main'].includes(o.id));recomputeGeometry(p);assert.equal(active(p,'collision').length,0);const sofa=f.furniture.find(o=>o.id==='sofa-main')!,chair=f.furniture.find(o=>o.id==='chair-main')!;chair.position={...sofa.position};chair.rotation=45;recomputeGeometry(p);assert.equal(active(p,'collision').length,1);chair.elevation=200;recomputeGeometry(p);assert.equal(active(p,'collision').length,0);assert(p.geometry_diagnostics!.some(d=>d.rule==='collision'&&d.status==='resolved'));sofa.width=600;sofa.rotation=35;recomputeGeometry(p);assert.equal(active(p,'boundary').length,1);(f.walls[0] as any).curvePoint={x:20,y:20};recomputeGeometry(p);assert(active(p,'unknown').length>0);});
test('store transaction recomputes and archives stable IDs; replay and owner gates remain',async()=>{const store=new Store();await store.init();try{const p=await store.create('owner');const changed=await store.mutate(p.id,'owner','geometry-hit',0,'object_changed',{},q=>{q.scene.floors[0].furniture[0].width=1000;});const warning=changed.geometry_diagnostics!.find(d=>d.rule==='boundary')!;assert(warning);const fixed=await store.mutate(p.id,'owner','geometry-fix',1,'scene_changed',{},q=>{q.scene.floors[0].furniture=q.scene.floors[0].furniture.filter(o=>!warning.object_ids.includes(o.id));});assert.equal(fixed.geometry_diagnostics!.find(d=>d.id===warning.id)?.status,'resolved');await assert.rejects(store.get(p.id,'other'));}finally{await store.db.close();}});

test('invalid polygons and concave crossing are uncertain or boundary; floor metadata rejects',async()=>{const {polygon}=await import('../apps/api/geometry.js');const {Scene}=await import('../packages/contracts/index.js');const walls=(points:number[][])=>points.map((p,i)=>({start:{x:p[0],y:p[1]},end:{x:points[(i+1)%points.length][0],y:points[(i+1)%points.length][1]}}));
for(const pts of [[[0,0],[100,0],[100,0],[100,100],[0,100]],[[0,0],[100,0],[50,0],[100,100],[0,100]],[[0,0],[50,0],[100,0]],[[0,0],[100,100],[0,100],[100,0]],[[0,0],[100,0],[100,100],[0,0],[0,100]]])assert.equal(polygon(walls(pts)),null);
assert.equal(polygon([{start:{x:0,y:0},end:{x:100,y:0}},{start:{x:100,y:0},end:{x:100,y:100}},{start:{x:100,y:100},end:{x:20,y:20}}]),null);
const p=sampleProject('concave'),floor=p.scene.floors[0];p.rooms=[p.rooms[0]];const points=[[0,0],[400,0],[400,400],[250,400],[250,150],[150,150],[150,400],[0,400]];floor.walls=walls(points).map((w,i)=>({...w,id:`w${i}`,height:280,thickness:12,color:"#ffffff"}));p.rooms[0].wall_ids=floor.walls.map(w=>w.id);floor.furniture=[{...floor.furniture[0],position:{x:200,y:125},width:300,depth:150}];recomputeGeometry(p);assert(active(p,'boundary').length);const invalid=structuredClone(p.scene);(invalid.floors[0] as any).elevation='NaN';assert.equal(Scene.safeParse(invalid).success,false);
});
