import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {randomUUID} from 'node:crypto';import {ChatService} from '../apps/api/chat.js';import {Store} from '../apps/api/store.js';import {MediaService,decodeMedia} from '../apps/api/media.js';import {buildApp} from '../apps/api/app.js';
test('private media scope, magic, pending provenance, corrected audio and SSRF refusal',async()=>{
 const dir=process.env.RENOVATION_MEDIA_FIXTURES!;assert.ok(dir,'Run scripts/prepare-media-fixtures.py and set RENOVATION_MEDIA_FIXTURES');const png=readFileSync(resolve(dir,'green.png')),wav=readFileSync(resolve(dir,'public-speech.wav'));const store=new Store();await store.init();const p=await store.create('owner'),other=await store.create('other');let calls=0;
 let consultationCalls=0;const chat=new ChatService(store,async()=>{consultationCalls++;throw Error('test provider failure');});
 const service=new MediaService(store,async(_url,options)=>{calls++;const request=JSON.parse(String(options?.body));const audio=request.messages[0].content.some((c:any)=>c.type==='input_audio');assert.ok(request.messages[0].content.some((c:any)=>c.image_url?.url.includes(png.toString('base64'))||c.input_audio?.data===wav.toString('base64')));return new Response(JSON.stringify({choices:[{message:{content:audio?'Public audio transcript':JSON.stringify({candidates:[{field_key:'tone',value:'绿色',rationale:'全图绿色，不代表用户偏好'}]})}}]}));},chat);
 const command=()=>({request_id:randomUUID(),expected_version:q.version});let q=p;
 try{for(const [mime,data] of [['image/svg+xml','PHN2Zz4='],['image/png','PHN2Zz4='],['audio/wav','aGVsbG8=']])assert.throws(()=>decodeMedia(mime,data));assert.throws(()=>decodeMedia('image/png','A'.repeat(7000001)));
 q=await service.upload(p.id,'owner',{...command(),room_id:'living',mime:'image/png',data:png.toString('base64')});const image=q.attachments![0];await assert.rejects(()=>service.get(other.id,'other',image.id));await assert.rejects(()=>service.get(p.id,'other',image.id));assert.deepEqual(Buffer.from((await service.get(p.id,'owner',image.id)).data,'base64'),png);
 const analysis={...command(),attachment_id:image.id};q=await service.analyze(p.id,'owner',analysis);assert.equal(q.requirements.length,0);assert.equal(q.suggestions[0].status,'proposed');assert.ok(q.suggestions[0].evidence_ids.includes(image.id));q=await service.analyze(p.id,'owner',analysis);assert.equal(calls,1);
 q=await service.upload(p.id,'owner',{...command(),room_id:'living',mime:'audio/wav',data:wav.toString('base64')});const audio=q.attachments!.at(-1)!;q=await service.analyze(p.id,'owner',{...command(),attachment_id:audio.id});q=await service.confirm(p.id,'owner',{...command(),attachment_id:audio.id,transcript:'我纠正的原话',confirmed:true});assert.equal(q.messages.find(m=>m.role==='user')?.content,'我纠正的原话');await chat.active.get(p.id)?.promise;assert.equal(consultationCalls,1);assert.equal(q.attachments!.at(-1)?.transcript,'Public audio transcript');assert.deepEqual(Buffer.from((await service.get(p.id,'owner',audio.id)).data,'base64'),wav);
 const app=await buildApp(store,{assets:false,accessCode:'synthetic'});const login=await app.inject({method:'POST',url:'/api/session/login',payload:{code:'synthetic'}});const headers={cookie:login.cookies[0].name+'='+login.cookies[0].value};for(const url of ['http://127.0.0.1','https://[::1]','https://169.254.169.254','https://example.com/redirect'])assert.equal((await app.inject({method:'POST',url:`/api/projects/${p.id}/media/link`,headers,payload:{url}})).statusCode,422);await app.close();
 }finally{await chat.stop();await store.close();}
});

test('analysis durable claim deduplicates concurrent provider calls and sanitizes malformed output',async()=>{
 const store=new Store();await store.init();const p=await store.create('owner');const png=readFileSync(resolve(process.env.RENOVATION_MEDIA_FIXTURES!,'green.png'));let release!:()=>void;let entered!:()=>void;const started=new Promise<void>(r=>entered=r);const pause=new Promise<void>(r=>release=r);let calls=0;
 const media=new MediaService(store,async()=>{calls++;entered();await pause;return new Response(JSON.stringify({choices:[{message:{content:'not JSON private upstream detail'}}]}));});
 try{const q=await media.upload(p.id,'owner',{request_id:randomUUID(),expected_version:0,room_id:'living',mime:'image/png',data:png.toString('base64')});const b={request_id:randomUUID(),expected_version:q.version,attachment_id:q.attachments![0].id};const first=media.analyze(p.id,'owner',b);await started;const claimed=await store.get(p.id,'owner');await assert.rejects(()=>media.analyze(p.id,'owner',{...b,request_id:randomUUID(),expected_version:claimed.version}),/正在分析/);assert.equal((await store.get(p.id,'owner')).attachments![0].status,'analyzing');const second=media.analyze(p.id,'owner',b);release();const results=await Promise.allSettled([first,second]);assert.equal(calls,1);for(const r of results){assert.equal(r.status,'rejected');if(r.status==='rejected'){assert.equal(r.reason.statusCode,503);assert.match(r.reason.message,/格式无效/);assert.ok(!r.reason.message.includes('private'));}}const saved=await store.get(p.id,'owner');assert.equal(saved.attachments![0].status,'failed');assert.equal(saved.suggestions.length,0);await assert.rejects(()=>media.analyze(p.id,'owner',b),/新请求/);assert.equal(calls,1);assert.equal((await media.get(p.id,'owner',b.attachment_id)).data,png.toString('base64'));
 }finally{release?.();await store.close();}
});
