import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {Store} from '../apps/api/store.js';import {buildApp} from '../apps/api/app.js';import {ReferenceLines} from '../apps/api/references.js';
test('reference whitelist, owner/room binding, stable quantity IDs, replay and atomic exact adoption',async()=>{
 const store=new Store();await store.init();let calls=0;const app=await buildApp(store,{assets:false,accessCode:'synthetic',referenceGenerator:async()=>{calls++;return {lines:[{asset_id:'chair',quantity:2},{asset_id:'storage',quantity:1}],text:'参考，未采用'};}});
 try{assert.equal(ReferenceLines.safeParse([{asset_id:'remote-script',quantity:1}]).success,false);for(const n of [0,1.5,5])assert.equal(ReferenceLines.safeParse([{asset_id:'chair',quantity:n}]).success,false);
 const login=await app.inject({method:'POST',url:'/api/session/login',payload:{code:'synthetic'}});const headers={cookie:login.cookies[0].name+'='+login.cookies[0].value};const p=await store.create('owner');const other=await store.create('other');
 const post=(path:string,body:any,id=p.id)=>app.inject({method:'POST',url:`/api/projects/${id}/references${path}`,headers,payload:body});
 const b={request_id:randomUUID(),expected_version:0,room_id:'living',text:'两把椅子和一个柜子'};
 assert.equal((await post('',b,other.id)).statusCode,404);assert.equal((await app.inject({url:`/api/projects/${other.id}`,headers})).statusCode,404);assert.equal((await post('',{...b,room_id:'absent'})).statusCode,404);
 let r=await post('',b);assert.equal(r.statusCode,200,r.body);let q=r.json();const plan=q.reference_plans[0];const originalIds=plan.lines[0].object_ids;
 const tampered=structuredClone(q.scene);tampered.floors[0].furniture.find((o:any)=>o.suggestion_id).reference_status='accepted';assert.equal((await app.inject({method:'POST',url:`/api/projects/${p.id}/scene/save`,headers,payload:{scene:tampered,expected_version:q.version,request_id:randomUUID()}})).statusCode,409);assert.equal(q.scene.floors[0].furniture.length,p.scene.floors[0].furniture.length+3);assert.deepEqual(q.requirements,p.requirements);assert.equal((await post('',b)).statusCode,200);assert.equal(calls,1);
 const qty=(quantity:number)=>({request_id:randomUUID(),expected_version:q.version,room_id:'living',plan_id:plan.id,asset_id:'chair',quantity});
 const shrink=qty(1);q=(await post('/quantity',shrink)).json();assert.equal((await post('/quantity',shrink)).json().version,q.version);q=(await post('/quantity',qty(2))).json();assert.deepEqual(q.reference_plans[0].lines[0].object_ids,originalIds);
 const ids=q.reference_plans[0].lines.flatMap((l:any)=>l.object_ids);const decision={request_id:randomUUID(),expected_version:q.version,room_id:'living',plan_id:plan.id,object_ids:ids,action:'accept',confirmed:true};
 assert.equal((await post('/decision',{...decision,room_id:'room2'})).statusCode,404);assert.equal((await post('/decision',{...decision,confirmed:false})).statusCode,400);assert.equal((await post('/decision',{...decision,object_ids:[ids[0],'sofa-main']})).statusCode,409);assert.equal((await store.get(p.id,'owner')).version,q.version);
 assert.equal((await post('/decision',{...decision,expected_version:q.version-1})).statusCode,409);
 const oldPosition=structuredClone(q.scene.floors[0].furniture.find((o:any)=>o.id===ids[0]).position);
 const moved=await store.mutate(p.id,'owner',randomUUID(),q.version,'scene_changed',{},p=>{p.scene.floors[0].furniture.find(o=>o.id===ids[0])!.position.x=600;});assert.equal((await post('/decision',{...decision,expected_version:moved.version})).statusCode,409);
 q=await store.mutate(p.id,'owner',randomUUID(),moved.version,'scene_changed',{},p=>{p.scene.floors[0].furniture.find(o=>o.id===ids[0])!.position=oldPosition;});decision.expected_version=q.version;
 const accepted={...decision,object_ids:[ids[0],ids[1]]};r=await post('/decision',accepted);assert.equal(r.statusCode,200,r.body);q=r.json();assert.equal(q.requirements.length,p.requirements.length+2);assert.equal((await post('/decision',accepted)).json().version,q.version);
 const edited=await app.inject({method:'POST',url:`/api/projects/${p.id}/objects/update`,headers,payload:{expected_version:q.version,request_id:randomUUID(),room_id:'living',object_id:ids[0],confirmed:true,patch:{width:111}}});assert.equal(edited.statusCode,200,edited.body);q=edited.json();assert.equal(JSON.parse(q.requirements.find((r:any)=>r.field_key===`furniture:${ids[0]}`).value).width,111);
 const changedScene=structuredClone(q.scene);changedScene.floors[0].furniture.find((o:any)=>o.id===ids[0]).width=112;const saved=await app.inject({method:'POST',url:`/api/projects/${p.id}/scene/save`,headers,payload:{expected_version:q.version,request_id:randomUUID(),scene:changedScene}});assert.equal(saved.statusCode,200,saved.body);q=saved.json();assert.equal(JSON.parse(q.requirements.find((r:any)=>r.field_key===`furniture:${ids[0]}`).value).width,112);
 const beforeReq=structuredClone(q.requirements);q=(await post('/decision',{...decision,request_id:randomUUID(),expected_version:q.version,object_ids:[ids[2]],action:'remove'})).json();assert.deepEqual(q.requirements,beforeReq);assert.ok(q.scene.floors[0].furniture.some((o:any)=>o.id==='sofa-main'));assert.ok(q.scene.floors[0].furniture.some((o:any)=>o.id===ids[0]&&o.reference_status==='accepted'));
 assert.equal((await post('/decision',{...decision,request_id:randomUUID(),expected_version:q.version,object_ids:[ids[0]],action:'remove'})).statusCode,409);
 }finally{await app.close();await store.close();}
});
