import React,{useEffect,useRef,useState} from 'react';
import type { ProjectData } from '../../../packages/contracts/index.js';
import type { Commit } from './RequirementsPanel.js';

type DraftFile={key:string;name:string;file?:File;attachmentId?:string;status:'queued'|'uploading'|'reading'|'ready'|'failed';error?:string;preview?:string};
export const fileMime=(file:File)=>({pdf:'application/pdf',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',txt:'text/plain',md:'text/markdown',csv:'text/csv',json:'application/json',wav:'audio/wav',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp'} as Record<string,string>)[file.name.split('.').at(-1)?.toLowerCase()??'']??file.type;
const supported=new Set(['image/png','image/jpeg','image/webp','audio/wav','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text/plain','text/markdown','text/csv','application/json']);
async function base64(blob:Blob){const bytes=new Uint8Array(await blob.arrayBuffer());let text='';for(let at=0;at<bytes.length;at+=8192)text+=String.fromCharCode(...bytes.subarray(at,at+8192));return btoa(text);}
async function normalizeImage(file:File){const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>40000000)throw Error('图片像素过多，请缩小后再上传');const scale=Math.min(1,2048/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('图片转换失败')),'image/png'));}finally{bitmap.close();}}
async function toWav(blob:Blob){const context=new AudioContext();try{const decoded=await context.decodeAudioData(await blob.arrayBuffer());if(decoded.duration>60.3)throw Error('录音最多60秒');const length=Math.min(960000,Math.ceil(decoded.duration*16000)),offline=new OfflineAudioContext(1,length,16000),source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();const pcm=(await offline.startRendering()).getChannelData(0),buffer=new ArrayBuffer(44+pcm.length*2),view=new DataView(buffer);const str=(at:number,t:string)=>{for(let i=0;i<t.length;i++)view.setUint8(at+i,t.charCodeAt(i));};str(0,'RIFF');view.setUint32(4,36+pcm.length*2,true);str(8,'WAVEfmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,16000,true);view.setUint32(28,32000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);str(36,'data');view.setUint32(40,pcm.length*2,true);pcm.forEach((n,i)=>view.setInt16(44+i*2,Math.max(-1,Math.min(1,n))*32767,true));return new Blob([buffer],{type:'audio/wav'});}finally{await context.close();}}

export function ComposerMedia({project,roomId,visible,commit,selected,onSelection,onDictation,keyboard,children,sendButton,onWorking}:{project:ProjectData;roomId:string;visible:boolean;commit:Commit;selected:string[];onSelection:(ids:string[])=>void;onDictation:(text:string,id:string)=>void;keyboard:(v:boolean)=>void;children?:React.ReactNode;sendButton?:React.ReactNode;onWorking?:(v:boolean)=>void}){
 const [files,setFiles]=useState<DraftFile[]>([]),[menu,setMenu]=useState(false),[library,setLibrary]=useState(false),[error,setError]=useState(''),[recording,setRecording]=useState(false),[permission,setPermission]=useState(false),[seconds,setSeconds]=useState(0),[pending,setPending]=useState(0),[edits,setEdits]=useState<Record<string,string>>({});
 const imageInput=useRef<HTMLInputElement>(null),documentInput=useRef<HTMLInputElement>(null),audioInput=useRef<HTMLInputElement>(null),micButton=useRef<HTMLButtonElement>(null),alive=useRef(true),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),captureGeneration=useRef(0),counter=useRef<ReturnType<typeof setInterval>|null>(null),stopTimer=useRef<ReturnType<typeof setTimeout>|null>(null),chain=useRef<Promise<void>>(Promise.resolve()),urls=useRef<string[]>([]),removed=useRef(new Set<string>());
 const props=useRef({project,commit,selected,onSelection,onDictation});props.current={project,commit,selected,onSelection,onDictation};
 const captureToken=useRef<{cancelled:boolean}|null>(null);
 const patch=(key:string,value:Partial<DraftFile>)=>{if(alive.current)setFiles(rows=>rows.map(row=>row.key===key?{...row,...value}:row));};
 const clearTimers=()=>{if(counter.current)clearInterval(counter.current);if(stopTimer.current)clearTimeout(stopTimer.current);};
 const cancelCapture=()=>{captureGeneration.current++;if(captureToken.current)captureToken.current.cancelled=true;clearTimers();if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(alive.current){setRecording(false);setPermission(false);}};
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;cancelCapture();for(const url of urls.current)URL.revokeObjectURL(url);};},[]);
 useEffect(()=>{if(!visible){cancelCapture();setMenu(false);}},[visible,roomId]);
 useEffect(()=>{onWorking?.(pending>0||recording||permission);},[pending,recording,permission]);
 const appendSelection=(id:string)=>{if(!alive.current)return;const current=props.current.selected;if(current.includes(id))return;if(current.length>=6){setError('本轮最多引用6个附件；文件已保存在资料库，可下一轮再用。');return;}const next=[...current,id];props.current.selected=next;props.current.onSelection(next);};
 function enqueue(job:()=>Promise<void>){setPending(v=>v+1);chain.current=chain.current.then(job).catch(e=>{if(alive.current)setError((e as Error).message);}).finally(()=>{if(alive.current)setPending(v=>v-1);});}
 async function analyze(id:string,dictation=false){const meta=props.current.project.attachments?.find(a=>a.id===id);const path=meta&&!['image/png','audio/wav'].includes(meta.mime)?'/documents/retry':'/media/analyze';const p=await props.current.commit(path,{attachment_id:id});const a=p.attachments?.find(a=>a.id===id);if(a?.status==='failed')throw Error(a.extraction_note??'文件未读取成功，请补充文字或重点页');if(dictation&&a?.transcript&&alive.current)props.current.onDictation(a.corrected_transcript??a.transcript,id);return p;}
 async function processFile(key:string,file:File,original?:Blob,dictation=false){
   if(removed.current.has(key))return;patch(key,{status:'uploading',error:undefined});
   let attachmentId:string|undefined;
   try{
     const mime=fileMime(file);if(file.size>5*1024*1024)throw Error('单文件最多5MB');if(!supported.has(mime))throw Error('不支持该类型。可使用PNG/JPEG/WebP、WAV、PDF、DOCX、TXT、MD、CSV、JSON。');
     const request_id=key;let result:ProjectData;
     if(mime.startsWith('image/')||mime==='audio/wav'){
       const normalized=['image/jpeg','image/webp'].includes(mime)?await normalizeImage(file):file;
       const keep=original??(['image/jpeg','image/webp'].includes(mime)?new Blob([file],{type:mime}):undefined);
       result=await props.current.commit('/media',{request_id,room_id:roomId,mime:mime.startsWith('image/')?'image/png':'audio/wav',data:await base64(normalized),...(keep?{original:{mime:keep.type,data:await base64(keep)}}:{})});
     }else result=await props.current.commit('/documents',{request_id,room_id:roomId,mime,name:file.name.slice(0,160),data:await base64(file)});
     attachmentId=result.attachments?.find(a=>a.message_id===request_id)?.id;if(!attachmentId)throw Error('上传响应未包含可引用的附件；请刷新资料库核对');
     patch(key,{attachmentId,status:'reading'});if(!removed.current.has(key))appendSelection(attachmentId);
     if(mime.startsWith('image/')||dictation)await analyze(attachmentId,dictation&&!removed.current.has(key));
     const actual=result.attachments?.find(a=>a.id===attachmentId);
     patch(key,{status:actual?.status==='failed'?'failed':'ready',...(actual?.status==='failed'?{error:actual.extraction_note}:{}),file:undefined});
   }catch(e){patch(key,{status:'failed',error:(e as Error).message,attachmentId});}
 }
 function addFiles(incoming:FileList|File[]){setMenu(false);setError('');const batch=Array.from(incoming);if(batch.length>6){setError('一次最多添加6个文件');return;}for(const file of batch){const key=crypto.randomUUID(),mime=fileMime(file),preview=mime.startsWith('image/')?URL.createObjectURL(file):undefined;if(preview)urls.current.push(preview);setFiles(rows=>[...rows,{key,name:file.name,file,status:'queued',preview}]);enqueue(()=>processFile(key,file));}}
 async function startRecording(){
   setError('');setMenu(false);setPermission(true);const generation=++captureGeneration.current,token={cancelled:false};captureToken.current=token;
   try{
     if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder||!MediaRecorder.isTypeSupported('audio/webm'))throw Error('此浏览器不支持当前录音编码。请上传WAV或直接输入文字；不会假装已经开始录音。');
     const captured=await navigator.mediaDevices.getUserMedia({audio:true});
     if(!alive.current||generation!==captureGeneration.current){captured.getTracks().forEach(t=>t.stop());return;}
     stream.current=captured;const r=new MediaRecorder(captured,{mimeType:'audio/webm'});recorder.current=r;const chunks:Blob[]=[];
     r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
     r.onerror=()=>{cancelCapture();if(alive.current)setError('录音编码失败，原有附件保留。请重新录音或上传WAV。');};
     r.onstop=()=>{captured.getTracks().forEach(t=>t.stop());clearTimers();if(captureToken.current===token)captureToken.current=null;if(alive.current)setRecording(false);if(!alive.current||token.cancelled)return;const key=crypto.randomUUID(),name=`语音-${new Date().toISOString().slice(11,19).replaceAll(':','-')}.wav`;setFiles(rows=>[...rows,{key,name,status:'queued'}]);enqueue(async()=>{try{const original=new Blob(chunks,{type:'audio/webm'}),converted=await toWav(original);if(!alive.current||token.cancelled)return;await processFile(key,new File([converted],name,{type:'audio/wav'}),original,true);}catch(e){patch(key,{status:'failed',error:(e as Error).message});}});};
     r.start();setSeconds(0);setRecording(true);counter.current=setInterval(()=>setSeconds(s=>s+1),1000);stopTimer.current=setTimeout(()=>{if(r.state==='recording')r.stop();},60000);
   }catch(e){stream.current?.getTracks().forEach(t=>t.stop());if(alive.current){const name=(e as Error).name;setError(name==='NotAllowedError'?'麦克风权限被拒绝。请在浏览器中允许录音，或上传WAV、直接输入文字。':(e as Error).message);}}finally{if(alive.current&&generation===captureGeneration.current)setPermission(false);}
 }
 function remove(key:string,id?:string){removed.current.add(key);setFiles(rows=>rows.filter(row=>row.key!==key));if(id){const next=props.current.selected.filter(x=>x!==id);props.current.selected=next;props.current.onSelection(next);}}
 const history=(project.attachments??[]).filter(a=>a.room_id===roomId);
 return <div className="composer-media media-input" onFocusCapture={()=>keyboard(true)}
   onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))keyboard(false);}}
   onPaste={e=>{if(e.clipboardData.files.length){e.preventDefault();addFiles(e.clipboardData.files);}}}
   onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();}}
   onDrop={e=>{if(e.dataTransfer.files.length){e.preventDefault();addFiles(e.dataTransfer.files);}}}>
   <div className="composer-draft-files" aria-label="本轮附件">{files.filter(f=>!f.attachmentId||selected.includes(f.attachmentId)).map(f=><article key={f.key} className="composer-file" data-state={f.status}>{f.preview&&<img src={f.preview} alt={`待发送参考图：${f.name}`}/>}<div><strong>{f.name}</strong><small>{({queued:'等待处理',uploading:'正在上传',reading:'正在读取参考资料',ready:'已准备，尚未发送',failed:'处理未完成'} as const)[f.status]}</small>{f.error&&<p role="alert">{f.error}</p>}{f.status==='failed'&&<button type="button" onClick={()=>enqueue(async()=>{if(f.attachmentId){patch(f.key,{status:'reading',error:undefined});try{await analyze(f.attachmentId);patch(f.key,{status:'ready'});}catch(e){patch(f.key,{status:'failed',error:(e as Error).message});}}else if(f.file)await processFile(f.key,f.file);})}>重试读取</button>}</div><button type="button" aria-label={`移除本轮附件 ${f.name}`} onClick={()=>remove(f.key,f.attachmentId)}>×</button></article>)}{selected.filter(id=>!files.some(f=>f.attachmentId===id)).map(id=><span className="composer-selected" key={id}>已引用 {history.find(a=>a.id===id)?.name??'参考资料'}<button type="button" aria-label="取消引用附件" onClick={()=>onSelection(selected.filter(x=>x!==id))}>×</button></span>)}</div>
   {children}
   <div className="composer-toolbar" role="toolbar" aria-label="聊天输入工具栏">
     <div className="composer-add"><button type="button" aria-label="添加图片或附件" title="添加图片或附件" aria-expanded={menu} onClick={()=>setMenu(v=>!v)}>＋ <span>添加</span></button>{menu&&<div className="composer-add-menu" onKeyDown={e=>{if(e.key==='Escape'){setMenu(false);e.stopPropagation();}}}><button type="button" onClick={()=>{imageInput.current?.click();setMenu(false);}}>照片 / 参考图</button><button type="button" onClick={()=>{documentInput.current?.click();setMenu(false);}}>文档 / 户型资料</button><button type="button" onClick={()=>{audioInput.current?.click();setMenu(false);}}>音频文件（WAV）</button><small>5MB/文件；项目10个/20MB<br/>可拖拽或粘贴图片和文件</small></div>}</div>
     <input ref={imageInput} className="visually-hidden" type="file" aria-label="上传图片或音频" accept="image/png,image/jpeg,image/webp,audio/wav,.wav" multiple onChange={e=>{if(e.target.files)addFiles(e.target.files);e.target.value='';}}/>
     <input ref={documentInput} className="visually-hidden" type="file" aria-label="上传文档附件" accept=".pdf,.docx,.txt,.md,.csv,.json" multiple onChange={e=>{if(e.target.files)addFiles(e.target.files);e.target.value='';}}/>
     <input ref={audioInput} className="visually-hidden" type="file" aria-label="上传WAV音频" accept="audio/wav,.wav" onChange={e=>{if(e.target.files)addFiles(e.target.files);e.target.value='';}}/>
     {!recording?<button ref={micButton} type="button" aria-label="开始录音" disabled={permission} onClick={()=>void startRecording()}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect x="8" y="2" width="8" height="13" rx="4" stroke="currentColor" strokeWidth="1.7"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8" stroke="currentColor" strokeWidth="1.7"/></svg>{permission?'授权中…':'语音'}</button>:<><button type="button" className="record-stop" aria-label="停止录音" onClick={()=>recorder.current?.stop()}>■ 停止 {seconds}s</button><button type="button" aria-label="取消录音" onClick={()=>cancelCapture()}>取消</button></>}
     <button type="button" aria-label="语音与参考图片" aria-expanded={library} onClick={()=>setLibrary(v=>!v)}>资料 <span>{history.length}</span></button><span className="composer-hint">{recording?'最长60秒，转写后可编辑':pending?'附件处理中，原文仍可编辑':'建议由你确认'}</span>{sendButton}
   </div>
   {error&&<p className="composer-error" role="alert">{error}</p>}
   {library&&<div className="composer-library" aria-label="本房间参考资料"><p>原件私有保存。移除本轮引用不会删除项目原件；尚未读取成功的文件不会被Agent当作已理解。</p>{history.map(a=><article key={a.id}><strong>{a.name??(a.mime==='image/png'?'参考图 · 全图区域':'语音原件')} · {a.status==='confirmed'?'已确认':a.status==='failed'?'待处理':'未确认偏好'}</strong><a href={`/api/projects/${project.id}/media/${a.id}?original=1`} download>下载保留原件</a><button type="button" disabled={selected.includes(a.id)||selected.length>=6} onClick={()=>appendSelection(a.id)}>引用到本轮</button>{['image/png','audio/wav'].includes(a.mime)&&<button type="button" onClick={()=>enqueue(async()=>{await analyze(a.id);})}>{a.mime==='image/png'?'读取图片偏好候选':'转写音频'}</button>}{a.extraction_note&&<p>{a.extraction_note}</p>}{a.extracted_text&&<details><summary>已提取文档文字（不等于用户确认）</summary><pre>{a.extracted_text.slice(0,4000)}</pre></details>}{a.transcript&&<><label>纠正转写<textarea value={edits[a.id]??a.corrected_transcript??a.transcript} onChange={e=>setEdits({...edits,[a.id]:e.target.value})}/></label><button type="button" onClick={()=>{appendSelection(a.id);onDictation(edits[a.id]??a.corrected_transcript??a.transcript!,a.id);}}>放入输入框，编辑后发送</button><button type="button" onClick={()=>enqueue(async()=>{await props.current.commit('/media/confirm',{attachment_id:a.id,transcript:edits[a.id]??a.corrected_transcript??a.transcript,confirmed:true});})}>确认转写并咨询</button></>}{project.suggestions.filter(s=>s.evidence_ids.includes(a.id)&&s.status==='proposed').map(s=><div key={s.id}><p>未采用偏好：{String(s.value)}</p><p>{s.rationale} · 全图；不代表你喜欢全部内容</p><button type="button" onClick={()=>enqueue(async()=>{await props.current.commit('/suggestions/adopt',{suggestion_ids:[s.id]});})}>采用此图片偏好</button></div>)}</article>)}</div>}
 </div>;
}
