import React,{useEffect,useRef,useState} from 'react';
import type { ProjectData } from '../../../packages/contracts/index.js';
import type { DeliverySnapshot } from '../../../packages/contracts/intake.js';
import type { Commit } from './RequirementsPanel.js';
import { api } from './api.js';
export function DeliveryPanel({project,commit,onClose,onQuestionnaire}:{project:ProjectData;commit:Commit;onClose:()=>void;onQuestionnaire:()=>void}){
 const [audience,setAudience]=useState<'owner'|'designer'>('owner'),[preview,setPreview]=useState<DeliverySnapshot|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const close=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const old=document.activeElement as HTMLElement|null;close.current?.focus();return()=>old?.focus();},[]);
 useEffect(()=>{let alive=true;api<DeliverySnapshot>(`/api/projects/${project.id}/delivery?audience=${audience}`).then(r=>{if(alive){setPreview(r);setError('');}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[project.id,project.version,audience]);
 const snapshots=(project.delivery_snapshots??[]).filter(s=>s.audience===audience).slice().reverse();
 return <div className="intake-backdrop"><section className="intake-dialog delivery-dialog" role="dialog" aria-modal="true" aria-label="问卷交付清单" onKeyDown={e=>{if(e.key==='Escape'){onClose();e.stopPropagation();}if(e.key==='Tab'){const nodes=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],summary,select')).filter(n=>n.getClientRects().length);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}}}>
 <header><div><span className="eyebrow">FROM YOUR WORDS TO A DESIGN BRIEF</span><h2>问卷与交付清单</h2><p>同一份有来源的需求，分别呈现业主预期与设计师接手信息</p></div><button ref={close} type="button" aria-label="关闭交付清单" onClick={onClose}>×</button></header>
 <div className="intake-tools"><div className="delivery-audience" role="group" aria-label="交付受众"><button className={audience==='owner'?'active':''} type="button" onClick={()=>setAudience('owner')}>业主理解与预期</button><button className={audience==='designer'?'active':''} type="button" onClick={()=>setAudience('designer')}>设计师需求交接</button></div><button type="button" onClick={onQuestionnaire}>补充问卷 / 共享范围</button><button className="primary" type="button" disabled={busy||!preview||audience==='designer'&&preview.sharing==='未授权'} onClick={async()=>{setBusy(true);setError('');try{await commit('/delivery/snapshots',{audience});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'保存中…':'保存当前交付快照'}</button></div>
 {error&&<p className="ask-error" role="alert">{error}</p>}<div className="delivery-scroll">{preview&&<><p className="delivery-scope">{preview.sharing} · 项目 v{preview.project_version} / 任务书 v{preview.brief_version}。页面为实时草稿，下载使用固定快照。<br/>初访内容不等于施工批准；没有生成或验收的图与文件不会标为完成。</p>
 <div className="delivery-sections">{preview.sections.filter(s=>audience==='owner'?s.id.startsWith('U')||['D06','D07','D08','D09','D10'].includes(s.id):s.id.startsWith('D')).map(s=><section className="delivery-section" key={s.id}><header><h3>{s.id} / {s.title}</h3><span data-state={s.state}>{s.state==='ready'?'资料已齐备':s.state==='draft'?'草案 / 仍需复核':'待补充'}</span></header>{s.content.length?s.content.map((line,i)=><p key={i}>{line}</p>):<p className="muted">尚未收集，不能从示例家庭或AI推断中补造。</p>}<p className="delivery-next">下一步：{s.next_action}</p>{s.evidence_ids.length>0&&<details><summary>来源记录（{s.evidence_ids.length}）</summary>{s.evidence_ids.map(id=><blockquote key={id}>{preview.evidence.find(e=>e.id===id)?.quote??`来源 ${id}（原话未获当前视图共享授权）`}</blockquote>)}</details>}</section>)}</div>
 <details><summary>完整待处理清单（{preview.pending.length}）</summary>{preview.pending.map(q=><p key={`${q.room_id}:${q.question_id}`}><b>{q.question_id} · {q.state}</b> {q.question}<br/>负责人：{q.owner}；下一步：{q.next_action}</p>)}</details><details><summary>使用边界</summary>{preview.limits.map(t=><p key={t}>{t}</p>)}</details></>}
 <section className="delivery-versions"><h3>已保存的交付快照</h3>{!snapshots.length&&<p>尚未生成固定版本。保存后可下载JSON或Markdown；不会发送邮件或共享链接。</p>}{snapshots.map(s=><article key={s.id}><strong>任务书 v{s.brief_version} · {s.created_at.slice(0,19).replace('T',' ')}</strong><span>{s.brief_version===project.brief_version?'当前内容版本':'已过期，保留历史'}</span><a href={`/api/projects/${project.id}/delivery/snapshots/${s.id}?format=md`} download>下载Markdown</a><a href={`/api/projects/${project.id}/delivery/snapshots/${s.id}?format=json`} download>下载JSON</a>{s.audience==='designer'&&s.sharing_version!==preview?.sharing_version&&<small>共享授权已变化，此旧副本不可继续导出；请重新生成。</small>}</article>)}</section>
 </div></section></div>;
}
