import React, { useEffect, useState } from 'react';
import { api } from './api.js';
import type { ProjectData } from '../../../packages/contracts/index.js';

type Board = { project_id:string; project_name:string; project_version:number; brief_version:number; sharing:string; requirements:{id:string;room_id:string|null;room_name:string;label:string;value:string;state:string;source:string;evidence:{id:string;quote:string}[];object_id?:string}[]; budget:{target?:number;ceiling?:number;currency?:string;scope?:string;state:string}; pending:{question_id:string;room_id:string|null;question:string;state:string;owner:string;next_action:string}[]; suggestions:{id:string;room_id:string|null;object_id?:string;text:string;status:string;created_at:string}[] };
export function DesignerBoard({project,role,focusRoom,focusObject,onClose}:{project:ProjectData;role:'owner'|'designer';focusRoom:(id:string)=>void;focusObject:(id:string)=>void;onClose:()=>void}){
 const [board,setBoard]=useState<Board|null>(null),[error,setError]=useState(''),[invite,setInvite]=useState(''),[busy,setBusy]=useState(false),[room,setRoom]=useState<string>(''),[text,setText]=useState(''),[sent,setSent]=useState(false);
 useEffect(()=>{let alive=true;api<Board>(`/api/projects/${project.id}/designer-board`).then(v=>alive&&setBoard(v)).catch(e=>alive&&setError(e.message));return()=>{alive=false;}},[project.id,project.version]);
 async function createInvite(){setBusy(true);setError('');try{const r=await api<{code:string}>('/api/projects/'+project.id+'/collaboration/invite',{});setInvite(r.code)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function submit(){if(!text.trim())return;setBusy(true);setError('');try{await api(`/api/projects/${project.id}/collaboration/suggestions`,{room_id:room||null,text:text.trim(),expected_version:project.version,request_id:crypto.randomUUID()});setText('');setSent(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="collaboration-backdrop" onPointerDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="collaboration-dialog" role="dialog" aria-modal="true" aria-label="设计师看板"><header><div><span className="eyebrow">PROJECT COLLABORATION</span><h2>设计师看板</h2><p>{role==='designer'?'共享需求与空间定位 · 只读入口':'查看设计师接手视图与入口权限'}</p></div><button type="button" aria-label="关闭设计师看板" onClick={onClose}>×</button></header>
  {error&&<p className="collaboration-error" role="alert">{error}</p>}{!board?<p className="collaboration-loading">正在读取共享看板…</p>:<div className="collaboration-scroll"><div className="collaboration-summary"><div><span>共享范围</span><b>{board.sharing}</b></div><div><span>需求版本</span><b>v{board.project_version} / 任务书 v{board.brief_version}</b></div><div><span>待决项</span><b>{board.pending.length} 项</b></div></div>
  {role==='owner'&&<section className="collaboration-invite"><div><h3>设计师只读入口</h3><p>邀请码只绑定当前项目。重新生成会立即使旧码失效；请通过安全渠道发送给设计师。</p></div><button type="button" className="primary" disabled={busy} onClick={()=>void createInvite()}>{busy?'生成中…':'生成设计师邀请码'}</button>{invite&&<code className="invite-code" aria-label="设计师邀请码">{invite}</code>}</section>}
  <section className="collaboration-budget"><div><span>预算状态</span><strong>{board.budget.state}</strong></div><div><span>目标</span><b>{board.budget.target??'未填写'} {board.budget.currency??''}</b></div><div><span>硬上限</span><b>{board.budget.ceiling??'未填写'}</b></div><p>{board.budget.scope?`包含范围：${board.budget.scope}`:'包含范围尚未明确'} · 仅为业主意向，不是报价。</p></section>
  <section><div className="collaboration-section-head"><h3>共享需求</h3><span>{board.requirements.length} 项 · 点击卡片回看原话</span></div><div className="collaboration-requirements">{board.requirements.length?board.requirements.map(r=><article className="collaboration-card" key={r.id}><button type="button" className="collaboration-card-main" onClick={e=>{const d=(e.currentTarget.parentElement?.querySelector('details') as HTMLDetailsElement|null);if(d)d.open=!d.open}}><span className="collaboration-room">{r.room_name}</span><strong>{r.label}</strong><b>{r.value}</b><small>{r.source} · {r.state==='confirmed'?'已确认':'待核对'}</small></button>{r.evidence.length>0&&<details><summary>查看原话与来源（{r.evidence.length}）</summary>{r.evidence.map(e=><blockquote key={e.id}>{e.quote}</blockquote>)}</details>}{r.object_id&&<button type="button" className="link-button" onClick={()=>focusObject(r.object_id!)}>⌖ 定位关联家具 {r.object_id}</button>}{!r.object_id&&r.room_id&&<button type="button" className="link-button" onClick={()=>focusRoom(r.room_id!)}>⌖ 定位房间</button>}</article>):<p className="collaboration-empty">当前共享范围没有可展示的需求。业主尚未授权，或仍需在 Q06 明确共享范围。</p>}</div></section>
  <section><div className="collaboration-section-head"><h3>未决项</h3><span>不把缺口当成已确认</span></div><div className="collaboration-pending">{board.pending.slice(0,12).map(p=><article key={`${p.room_id}:${p.question_id}`}><b>{p.question_id} · {p.state}</b><span>{p.question}</span><small>负责人：{p.owner} · 下一步：{p.next_action}</small></article>)}</div></section>
  <section className="collaboration-suggestions"><div className="collaboration-section-head"><h3>设计师建议</h3><span>独立记录 · 不等于业主确认</span></div>{board.suggestions.map(s=><article key={s.id}><span>{s.room_id?project.rooms.find(r=>r.id===s.room_id)?.name:'全屋'}</span><p>{s.text}</p><small>设计师建议 · {s.status==='proposed'?'待业主确认':'已处理'}</small></article>)}{role==='designer'&&<div className="suggestion-form"><label>关联空间<select value={room} onChange={e=>setRoom(e.target.value)}><option value="">全屋</option>{project.rooms.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><label>建议内容<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="记录布局、尺寸或材料方向；不会写入业主正式需求。" maxLength={2000}/></label><button type="button" className="primary" disabled={busy||!text.trim()} onClick={()=>void submit()}>{busy?'提交中…':'提交设计建议'}</button>{sent&&<span role="status">已提交，等待业主确认。</span>}</div>}</section>
  </div>}</section></div>;
}
