import React,{useEffect,useRef,useState} from 'react';import type {ProjectData} from '../../../packages/contracts/index.js';import type {Commit} from './RequirementsPanel.js';
const base64=async(blob:Blob)=>{const bytes=new Uint8Array(await blob.arrayBuffer());let text='';for(let at=0;at<bytes.length;at+=8192)text+=String.fromCharCode(...bytes.subarray(at,at+8192));return btoa(text);};
async function wav(blob:Blob){const context=new AudioContext();try{const decoded=await context.decodeAudioData(await blob.arrayBuffer());if(decoded.duration>60)throw Error('最多录音60秒');const offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*16000),16000);const source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();const pcm=(await offline.startRendering()).getChannelData(0);const bytes=new ArrayBuffer(44+pcm.length*2),v=new DataView(bytes);const str=(at:number,t:string)=>{for(let i=0;i<t.length;i++)v.setUint8(at+i,t.charCodeAt(i));};str(0,'RIFF');v.setUint32(4,36+pcm.length*2,true);str(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,pcm.length*2,true);pcm.forEach((n,i)=>v.setInt16(44+i*2,Math.max(-1,Math.min(1,n))*32767,true));return new Blob([bytes],{type:'audio/wav'});}finally{await context.close();}}
async function normalizeImage(file:Blob){if(file.size>5*1024*1024)throw Error('图片原件最多5MB');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>40000000)throw Error('图片像素过多，请先缩小');const scale=Math.min(1,2048/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('图片解码失败，请上传PNG')),'image/png'));}finally{bitmap.close();}}
export function MediaInput({project,roomId,visible,commit}:{project:ProjectData;roomId:string;visible:boolean;commit:Commit}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[link,setLink]=useState(''),[edits,setEdits]=useState<Record<string,string>>({});const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),cancelled=useRef(false),alive=useRef(true),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const cleanup=()=>{cancelled.current=true;if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;cleanup();};},[]);useEffect(()=>{if(!visible){cleanup();setRecording(false);}},[visible,roomId]);
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();}catch(e){if(alive.current)setError((e as Error).message==='Not supported'?'当前浏览器录音不可用，请上传WAV或手动输入。':(e as Error).message);}finally{if(alive.current)setBusy(false);}};
 const upload=async(blob:Blob,mime:string,original?:Blob)=>{if(blob.size>5*1024*1024||(original&&original.size>5*1024*1024))throw Error('单个文件最多5MB');await commit('/media',{room_id:roomId,mime,data:await base64(blob),...(original?{original:{mime:original.type,data:await base64(original)}}:{})});};
 return <details className="media-input"><summary>语音与参考图片</summary><p>PNG/JPEG/WebP ≤5MB；JPEG/WebP在浏览器解码并缩至最长2048像素PNG，原件私有保留；WAV为16kHz单声道PCM，最长60秒。解读仅为候选。</p>
 <label>上传图片或音频<input type="file" accept="image/png,image/jpeg,image/webp,audio/wav,.wav" disabled={busy||recording} onChange={e=>{const file=e.target.files?.[0];if(file)void act(async()=>{if(['image/jpeg','image/webp'].includes(file.type))await upload(await normalizeImage(file),'image/png',file);else await upload(file,file.name.toLowerCase().endsWith('.wav')?'audio/wav':file.type);});e.target.value='';}}/></label>
 <button disabled={busy||recording} onClick={()=>void act(async()=>{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder||!MediaRecorder.isTypeSupported('audio/webm'))throw Error('此浏览器不支持录音，请上传WAV或手动输入');cancelled.current=false;const captured=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current||cancelled.current){captured.getTracks().forEach(t=>t.stop());return;}stream.current=captured;try{const r=new MediaRecorder(captured,{mimeType:'audio/webm'});recorder.current=r;const chunks:Blob[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onerror=()=>{cleanup();if(alive.current){setRecording(false);setError('录音编码失败，原有附件未改变，请上传WAV或重试。');}};r.onstop=()=>{captured.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);if(alive.current)setRecording(false);if(!cancelled.current&&alive.current)void act(async()=>{const original=new Blob(chunks,{type:'audio/webm'});const converted=await wav(original);if(!cancelled.current&&alive.current)await upload(converted,'audio/wav',original);});};r.start();setRecording(true);timer.current=setTimeout(()=>r.state==='recording'&&r.stop(),60000);}catch(e){captured.getTracks().forEach(t=>t.stop());throw e;}}).catch(()=>{})}>开始录音</button>
 <button disabled={!recording} onClick={()=>recorder.current?.stop()}>停止录音</button><button disabled={!recording} onClick={()=>{cleanup();setRecording(false);}}>取消录音</button>
 <label>HTTPS图片链接<input value={link} onChange={e=>setLink(e.target.value)} placeholder="此版本不抓取链接，请上传图片"/></label><button disabled={busy||!link} onClick={()=>void act(()=>commit('/media/link',{url:link}))}>检查图片链接</button>
 {(project.attachments??[]).filter(a=>a.room_id===roomId).map(a=><article key={a.id}><p>{a.mime==='image/png'?'参考图 · 全图区域':'语音原件'} · {a.status==='confirmed'?'已确认':'待确认'}</p><a href={`/api/projects/${project.id}/media/${a.id}?original=1`} download>下载保留原件</a><button disabled={busy} onClick={()=>void act(()=>commit('/media/analyze',{attachment_id:a.id}))}>{a.mime==='image/png'?'读取图片偏好候选':'转写音频'}</button>{a.transcript&&<><label>纠正转写<textarea value={edits[a.id]??a.corrected_transcript??a.transcript} onChange={e=>setEdits({...edits,[a.id]:e.target.value})}/></label><button disabled={busy} onClick={()=>void act(()=>commit('/media/confirm',{attachment_id:a.id,transcript:edits[a.id]??a.corrected_transcript??a.transcript,confirmed:true}))}>确认转写并咨询</button></>}{project.suggestions.filter(s=>s.evidence_ids.includes(a.id)&&s.status==='proposed').map(s=><div key={s.id}><p>未采用偏好：{String(s.value)}</p><p>{s.rationale} · 全图；不代表你喜欢全部内容</p><button disabled={busy} onClick={()=>void act(()=>commit('/suggestions/adopt',{suggestion_ids:[s.id]}))}>采用此图片偏好</button></div>)}</article>)}
 {error&&<p role="alert">{error.includes('Permission')||error.includes('denied')?'麦克风权限被拒绝，请允许录音或上传WAV、手动输入。':error}</p>}</details>;
}
