import React,{useEffect,useRef,useState} from 'react';
import type { ProjectData } from '../../../packages/contracts/index.js';
import type { IntakeAnswer, IntakeDefinition, IntakeQuestion } from '../../../packages/contracts/intake.js';
import type { Commit } from './RequirementsPanel.js';
import { api } from './api.js';
import { IntakeCard } from './IntakeCard.js';
type Item=IntakeDefinition&{applicable:boolean;answer:IntakeAnswer|null;card:IntakeQuestion};
export function QuestionnairePanel({project,roomId,commit,keyboard,onClose}:{project:ProjectData;roomId:string;commit:Commit;keyboard:(v:boolean)=>void;onClose:()=>void}){
 const [items,setItems]=useState<Item[]>([]),[selectedRoom,setRoom]=useState(roomId),[active,setActive]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[search,setSearch]=useState('');
 const close=useRef<HTMLButtonElement>(null);useEffect(()=>{const old=document.activeElement as HTMLElement|null;close.current?.focus();return()=>{keyboard(false);old?.focus();};},[]);
 useEffect(()=>{let alive=true;api<{items:Item[]}>(`/api/projects/${project.id}/intake?room_id=${selectedRoom}`).then(r=>{if(alive){setItems(r.items);setError('');}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[project.id,project.version,selectedRoom]);
 const applicable=items.filter(i=>i.applicable),confirmed=applicable.filter(i=>i.answer?.answer_state==='answered'&&i.answer.confirmation_state==='confirmed').length;
 const shown=items.filter(i=>(!search||`${i.id} ${i.question} ${i.group}`.includes(search))&&(filter==='all'||filter==='pending'&&(!i.answer||i.answer.confirmation_state==='pending'||i.answer.answer_state==='unknown')||filter==='conditional'&&i.conditional||filter==='answered'&&i.answer?.answer_state==='answered'));
 const current=items.find(i=>i.id===active);
 const dirty=useRef(false);
 const navigate=(action:()=>void)=>{if(dirty.current&&!window.confirm('当前题目有未保存的草稿。离开会丢弃本题草稿；取消可继续填写。'))return;dirty.current=false;action();};
 return <div className="intake-backdrop" onPointerDown={e=>{if(e.target===e.currentTarget)navigate(onClose);}}><section className="intake-dialog" role="dialog" aria-modal="true" aria-label="完整需求问卷" onKeyDown={e=>{if(e.key==='Escape'){navigate(onClose);e.stopPropagation();}if(e.key==='Tab'){const nodes=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select,textarea,summary,a[href]')).filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}>
 <header><div><span className="eyebrow">YOUR HOME · YOUR CHOICES</span><h2>完整需求问卷</h2><p>48道基础题 + 12个条件分支；不必一次答完</p></div><button ref={close} type="button" onClick={()=>navigate(onClose)} aria-label="关闭完整问卷">×</button></header>
 <div className="intake-tools"><label>当前房间<select aria-label="问卷房间" value={selectedRoom} onChange={e=>{const next=e.target.value;navigate(()=>{setRoom(next);setActive('');});}}>{project.rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>筛选<select aria-label="问卷筛选" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部60题</option><option value="pending">待补充 / 待核对</option><option value="answered">已经回答</option><option value="conditional">条件分支</option></select></label><input aria-label="搜索问卷" placeholder="搜索题号、问题或分组" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <p className="intake-progress">当前适用 {applicable.length} 项，明确回答 {confirmed} 项。未知、跳过、待核对均不计为已明确。</p>
 {error&&<p role="alert">{error}</p>}<div className="intake-layout"><nav aria-label="问卷题目索引">{shown.map(i=><button type="button" key={i.id} className={active===i.id?'active':''} onClick={()=>{if(active!==i.id)navigate(()=>setActive(i.id));}}><span>{i.id} · {i.scope==='project'?'全屋':'本房间'} · {i.group}</span><strong>{i.question}</strong><small>{!i.applicable?'尚未触发，可主动填写':!i.answer?'未收集':i.answer.confirmation_state==='pending'?'原话待核对':i.answer.answer_state==='answered'?'已明确':i.answer.answer_state==='unknown'?'暂不确定':i.answer.answer_state==='skipped'?'已跳过':'不适用'}</small></button>)}</nav><main className="intake-editor">{current?<IntakeCard key={`${selectedRoom}:${current.id}`} project={project} question={current.card} answer={current.answer} roomId={selectedRoom} commit={commit} keyboard={keyboard} onDirty={(_id,value)=>{dirty.current=value;}} onDone={()=>{dirty.current=false;setActive('');}}/>:<div className="intake-empty"><h3>从最有把握的部分开始</h3><p>选择题目可查看推荐方向、三个替代选项与自由填写区。已有对话提取会标记为“待核对”，不会替你确认。</p><p>重要缺口可以记录负责人和下一步；正式任务书会保留这些待处理事项。</p></div>}</main></div>
 </section></div>;
}
