import React,{useRef,useState} from 'react';
import type {ProjectData} from '../../../packages/contracts/index.js';
import type {Commit} from './RequirementsPanel.js';
export function ReferencePanel({project,roomId,commit}:{project:ProjectData;roomId:string;commit:Commit}){
 const [text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const [scope,setScope]=useState<{plan_id:string;object_ids:string[];version:number}|null>(null);const dialog=useRef<HTMLDialogElement>(null);
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const items=project.scene.floors.flatMap(f=>f.furniture);
 const open=(plan_id:string,object_ids:string[])=>{setScope({plan_id,object_ids,version:project.version});dialog.current?.showModal();};
 return <section className="reference-panel" aria-label="参考家具方案"><h3>参考家具 · 由你决定</h3><p>参考摆放不等于正式需求；采用只确认列出的家具属性。</p>
 <form onSubmit={e=>{e.preventDefault();void act(()=>commit('/references',{room_id:roomId,text}));}}><label>希望添加的参考家具<textarea required maxLength={4000} value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={busy||!text.trim()}>{busy?'处理中…':'生成参考家具'}</button></form>
 {(project.reference_plans??[]).filter(s=>s.room_id===roomId).map(s=>{const objects=items.filter(o=>o.suggestion_id===s.id);const pending=objects.filter(o=>o.reference_status==='pending');return <article key={s.id}><p>{s.raw_text}</p><p>{s.text||'生成中…'}</p>{s.lines.map(l=><label key={l.asset_id}>{l.asset_id} 目标数量（当前场景 {objects.filter(o=>o.catalogId===l.asset_id).length} 件；调整可恢复移除的参考）<input type="number" min={1} max={4} defaultValue={l.quantity} key={`${l.asset_id}-${l.quantity}`} disabled={busy||objects.some(o=>o.catalogId===l.asset_id&&o.reference_status==='accepted')} onBlur={e=>{const quantity=Number(e.target.value);if(quantity!==l.quantity)void act(()=>commit('/references/quantity',{room_id:roomId,plan_id:s.id,asset_id:l.asset_id,quantity}));}}/></label>)}
 {objects.map(o=><div className="reference-object" key={o.id}><strong>{o.reference_status==='pending'?'未采用 · 参考家具':'已采用家具'}</strong><p>{o.catalogId} · {o.id}</p><p>{String(o.width)}×{String(o.depth)}×{String(o.height)} cm</p>{o.reference_status==='pending'&&<><button disabled={busy} onClick={()=>open(s.id,[o.id])}>采用此家具</button><button disabled={busy} onClick={()=>void act(()=>commit('/references/decision',{room_id:roomId,plan_id:s.id,object_ids:[o.id],action:'remove'}))}>移除此参考</button></>}</div>)}
 {pending.length>0&&<button disabled={busy} onClick={()=>open(s.id,pending.map(o=>o.id))}>采用本组参考家具（{pending.length}件）</button>}</article>;})}
 <dialog ref={dialog} className="reference-scope" aria-label="确认参考家具范围" onCancel={()=>setScope(null)}><h3>确认采用范围</h3><p>房间 {roomId}；仅以下对象的资产、数量和当前属性。不覆盖其他需求。</p>{scope?.object_ids.map(id=>{const o=items.find(o=>o.id===id);return <p key={id}>{id} · {o?.catalogId} · 宽{String(o?.width)} / 深{String(o?.depth)} / 高{String(o?.height)} cm · 离地{String(o?.elevation??0)} cm · {String(o?.color)}</p>;})}<button disabled={busy} onClick={()=>{dialog.current?.close();setScope(null);}}>暂不采用</button><button disabled={busy||!scope||project.version!==scope.version} onClick={()=>void act(async()=>{await commit('/references/decision',{room_id:roomId,plan_id:scope!.plan_id,object_ids:scope!.object_ids,action:'accept',confirmed:true,expected_version:scope!.version});dialog.current?.close();setScope(null);})}>确认采用列出范围</button>{scope&&project.version!==scope.version&&<p role="alert">项目已变化，请关闭后重新查看范围。</p>}</dialog>
 {error&&<p role="alert">{error}</p>}</section>;
}
