"""Reproducible synthetic PNG + Google public speech fixture; no homeowner media."""
import hashlib, pathlib, struct, urllib.request, wave, zlib, argparse
p=argparse.ArgumentParser();p.add_argument('--output',required=True);args=p.parse_args();out=pathlib.Path(args.output);out.mkdir(parents=True,exist_ok=True)
def chunk(kind,data):return struct.pack('>I',len(data))+kind+data+struct.pack('>I',zlib.crc32(kind+data)&0xffffffff)
png=b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',64,64,8,2,0,0,0))+chunk(b'IDAT',zlib.compress((b'\0'+b'\0\x99\0'*64)*64))+chunk(b'IEND',b'')
(out/'green.png').write_bytes(png)
url='https://storage.googleapis.com/cloud-samples-data/speech/brooklyn_bridge.raw'
raw=urllib.request.urlopen(url,timeout=20).read(2000000)
assert hashlib.sha256(raw).hexdigest()=='f03f96d83ce63cf8a2783557edda141fb41480bcca88a8c67cfbdfed12dda29b'
with wave.open(str(out/'public-speech.wav'),'wb') as w:w.setnchannels(1);w.setsampwidth(2);w.setframerate(16000);w.writeframes(raw)
(out/'PROVENANCE.txt').write_text('green.png: synthetic solid green RGB, generated by this script.\npublic-speech.wav: Google public speech quickstart PCM, not synthesized or homeowner audio.\nSource: '+url+'\nSHA256 PCM: '+hashlib.sha256(raw).hexdigest()+'\n')
